export const PRODUCTS_LISTING_TYPES = {
    ADD_PRODUCTS_LIST: 'add-products-list/ADD_PRODUCTS_LIST',
    ADD_PRODUCTS_PAGE_LIMIT: 'add-products-page-limit/ADD_PRODUCTS_PAGE_LIMIT',
    ADD_PRODUCTS_CART_UPDATE: 'ADD_PRODUCTS_CART_UPDATE'
};